name: Build and deploy Node.js app to Azure Web App - Flipzon




on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:



      - name: printing ls command
      

        run: |
          cd..
          ls
