name: hello-world
on: push
env: 
    TEST : git diff --name-only HEAD HEAD^
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 2
      - id: files       
        run: |
          TEST
        

           
        
