name: hello-world
on: 
 push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 2
      - id: files       
        run: |
             files=`git diff --name-only HEAD HEAD^`
               for file in $files; do
                echo "hii" $file
                 if [ $file==*"trans/abc.html"* ];
                  then
                   echo "Dont do  ${file}."
                   else
                      echo "Do something with this ${file}."
                    fi 
                   done       
    
        
        
        
        
         
         
             
       
              
              


           
        
