name: hello-world
on: push
env:
  PATH: "zenTask/translation/test.yml"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run:
            if echo "${{ env.PATH}}" grep -q "translation" then
              echo "Hello"
        
