name: Skip Cypress for translation files
on:
  push:
    branches:
      - main

env:
  # decrease the timeout for Github Actions Cache, as it sometimes fails, causing wasted time
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3

jobs:
  skip_cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check for list of changed files
        run: |
          git fetch origin main --depth 1
          git diff --name-only ${{ github.sha }} .github/workflows
